---
title: Start Bootstrap
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Web Developer - Graphic Artist - User Experience Designer

'
baseurl: "/startbootstrap-freelancer-jekyll"
url: http://yourdomain.com
twitter_username: SBootstrap
github_username: BlackrockDigital
facebook_username: StartBootstrap
address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201
markdown: kramdown
